site_name: '🗝: `dtyper`: Fix and improve `typer` 🗝'

theme:
  name: material

  palette:
    primary:
      'deepPurple'

  font:
    text:
      Roboto
    code:
      Roboto Mono

extra_css: [extra.css]

plugins:
    - mkdocstrings
